[package]
name = "covrep"
version = "0.1.0"
authors = ["Benjamin MÃ¼ller <ben.mueller@me.com>"]

[dependencies]
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
reqwest = "0.8.2"
clap = "2.29.0"
hyper = "0.11.9"